In [1]:
L = list(range(10))
print(L)
type(L[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


int

In [11]:
import numpy as np
A = np.array([range(i, i+2) for i in [2,4,6]])
B = np.array([range(i, i+3) for i in [2,4]])

D = np.zeros(10, dtype=int)
np.ones((4,4), dtype=int)
C = np.random.random((3,3))
print(A)
print(B)
print(D)

[[2 3]
 [4 5]
 [6 7]]
[[2 3 4]
 [4 5 6]]
[0 0 0 0 0 0 0 0 0 0]


In [62]:
np.random.seed(0)

A = np.random.randint(0,10, size = (1,4,5))
B = np.random.randint(0,10,size=(1,3,3))

print(B)

[[[5 9 8]
  [9 4 3]
  [0 3 5]]]


In [85]:

print(B)

sub = B[0,1:,2:]
print(sub)


[[[5 9 8]
  [9 4 3]
  [0 3 5]]]
[[3]
 [5]]


In [16]:
sub[1,0] = 2
print(sub)


NameError: name 'sub' is not defined

In [26]:
array = []
for x in [1,2,3]:
    array.append([range(i,i+2) for i in [1,2,3]])
    print(array)

[[range(1, 3), range(2, 4), range(3, 5)]]
[[range(1, 3), range(2, 4), range(3, 5)], [range(1, 3), range(2, 4), range(3, 5)]]
[[range(1, 3), range(2, 4), range(3, 5)], [range(1, 3), range(2, 4), range(3, 5)], [range(1, 3), range(2, 4), range(3, 5)]]


In [76]:
import pandas as pd

# Create empty dataframe
df = pd.DataFrame()

# Create a column
df['name'] = ['John', 'Steve', 'Sarah']
df['gender'] = ['Male', 'Male', 'Female']
df['age'] = [31, 32, 19]


df.groupby('gender').min()

name  age
gender            
Female  Sarah   19
Male     John   31

In [70]:
def mean_age_by_group(df, col):
    return df.groupby(col).mean()

print(mean_age_by_group(df,'gender'))

         age
gender      
Female  19.0
Male    31.5


In [79]:
def upper_case_columns(df) :
    df.columns = df.columns.str.upper()
    return df

print(df.columns)

Index(['name', 'gender', 'age'], dtype='object')


In [80]:
df.pipe(mean_age_by_group,'gender').pipe(upper_case_columns)

AGE
gender      
Female  19.0
Male    31.5

In [81]:
commander_names = ["Alan Brooke", "George Marshall", "Frank Jack Fletcher", "Conrad Helfrich", "Albert Kesselring"] 
print(commander_names)

['Alan Brooke', 'George Marshall', 'Frank Jack Fletcher', 'Conrad Helfrich', 'Albert Kesselring']


In [82]:
print(commander_names[1].split(" "))

['George', 'Marshall']


In [83]:
# Sort a variable called 'commander_names' by the last elements of each name.
sorted(commander_names, key=lambda x: x.split(" ")[-1])

['Alan Brooke',
 'Frank Jack Fletcher',
 'Conrad Helfrich',
 'Albert Kesselring',
 'George Marshall']